[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ Orange Dark"

[colors]
foreground = "#d7e0e3"
background = "#242a2c"
cursor_bg = "#ff9820"
cursor_border = "#ff9820"
cursor_fg = "#242a2c"
selection_bg = "#383e41"
selection_fg = "#d7e0e3"
split = "#ff9820"
compose_cursor = "#ff7a46"
scrollbar_thumb = "#868e90"

ansi = [
  "#383e41", # black
  "#9ea6a9", # dark_red
  "#868e90", # dark_green
  "#ff8933", # dark_yellow
  "#9ea6a9", # dark_blue
  "#868e90", # dark_magenta
  "#9ea6a9", # dark_cyan
  "#9ea6a9" # light_gray
]

brights = [
  "#585f61", # gray
  "#9ea6a9", # red
  "#868e90", # green
  "#ff9820", # yellow
  "#9ea6a9", # blue
  "#868e90", # magenta
  "#9ea6a9", # cyan
  "#9ea6a9" # white
]

[colors.tab_bar]
inactive_tab_edge = "#161c1e"
background = "#242a2c"

[colors.tab_bar.active_tab]
fg_color = "#242a2c"
bg_color = "#ff9820"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#242a2c"
bg_color = "#383e41"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#242a2c"
bg_color = "#2d3436"

[colors.tab_bar.new_tab]
fg_color = "#242a2c"
bg_color = "#3aa85b"

[colors.tab_bar.new_tab_hover]
fg_color = "#242a2c"
bg_color = "#2d3436"
intensity = "Bold"