[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ Orange Dark"

[colors]
foreground = "#afd4ea"
background = "#1f303b"
cursor_bg = "#fc8e05"
cursor_border = "#fc8e05"
cursor_fg = "#1f303b"
selection_bg = "#384b56"
selection_fg = "#afd4ea"
split = "#fc8e05"
compose_cursor = "#ef632c"
scrollbar_thumb = "#63859a"

ansi = [
  "#47687c", # black
  "#7295aa", # dark_red
  "#63859a", # dark_green
  "#f37513", # dark_yellow
  "#55778b", # dark_blue
  "#63859a", # dark_magenta
  "#7295aa", # dark_cyan
  "#90b4c9" # light_gray
]

brights = [
  "#47687c", # gray
  "#7295aa", # red
  "#63859a", # green
  "#fc8e05", # yellow
  "#55778b", # blue
  "#63859a", # magenta
  "#7295aa", # cyan
  "#9fc4da" # white
]

[colors.tab_bar]
inactive_tab_edge = "#13242e"
background = "#1f303b"

[colors.tab_bar.active_tab]
fg_color = "#1f303b"
bg_color = "#fc8e05"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#1f303b"
bg_color = "#384b56"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#1f303b"
bg_color = "#2b3d48"

[colors.tab_bar.new_tab]
fg_color = "#1f303b"
bg_color = "#3aa85b"

[colors.tab_bar.new_tab_hover]
fg_color = "#1f303b"
bg_color = "#2b3d48"
intensity = "Bold"