[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ Mono Light"

[colors]
foreground = "#161616"
background = "#fcfcfc"
cursor_bg = "#2e2e2e"
cursor_border = "#2e2e2e"
cursor_fg = "#fcfcfc"
selection_bg = "#dedede"
selection_fg = "#161616"
split = "#2e2e2e"
compose_cursor = "#f14d4c"
scrollbar_thumb = "#525252"

ansi = [
  "#3d3d3d", # black
  "#a4a4a4", # dark_red
  "#868686", # dark_green
  "#868686", # dark_yellow
  "#a4a4a4", # dark_blue
  "#868686", # dark_magenta
  "#a4a4a4", # dark_cyan
  "#a4a4a4" # light_gray
]

brights = [
  "#525252", # gray
  "#a4a4a4", # red
  "#868686", # green
  "#868686", # yellow
  "#a4a4a4", # blue
  "#868686", # magenta
  "#a4a4a4", # cyan
  "#a4a4a4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#eeeeee"
background = "#fcfcfc"

[colors.tab_bar.active_tab]
fg_color = "#eeeeee"
bg_color = "#2e2e2e"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#eeeeee"
bg_color = "#dedede"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#eeeeee"
bg_color = "#eeeeee"

[colors.tab_bar.new_tab]
fg_color = "#eeeeee"
bg_color = "#819e00"

[colors.tab_bar.new_tab_hover]
fg_color = "#eeeeee"
bg_color = "#eeeeee"
intensity = "Bold"