[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ 47 Light"

[colors]
foreground = "#20231b"
background = "#f3eadd"
cursor_bg = "#00936b"
cursor_border = "#00936b"
cursor_fg = "#f3eadd"
selection_bg = "#dfd6c9"
selection_fg = "#20231b"
split = "#00936b"
compose_cursor = "#f0532b"
scrollbar_thumb = "#5d684c"

ansi = [
  "#5d684c", # black
  "#98a485", # dark_red
  "#00936b", # dark_green
  "#ec5a00", # dark_yellow
  "#6b765a", # dark_blue
  "#7a8568", # dark_magenta
  "#98a485", # dark_cyan
  "#dfd6c9" # light_gray
]

brights = [
  "#5d684c", # gray
  "#98a485", # red
  "#00936b", # green
  "#ec5a00", # yellow
  "#6b765a", # blue
  "#7a8568", # magenta
  "#98a485", # cyan
  "#e6dcd0" # white
]

[colors.tab_bar]
inactive_tab_edge = "#e6dcd0"
background = "#f3eadd"

[colors.tab_bar.active_tab]
fg_color = "#e6dcd0"
bg_color = "#00936b"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e6dcd0"
bg_color = "#dfd6c9"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e6dcd0"
bg_color = "#e6dcd0"

[colors.tab_bar.new_tab]
fg_color = "#e6dcd0"
bg_color = "#00936b"

[colors.tab_bar.new_tab_hover]
fg_color = "#e6dcd0"
bg_color = "#e6dcd0"
intensity = "Bold"