[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ Orange Light"

[colors]
foreground = "#2e404b"
background = "#cde1ee"
cursor_bg = "#ff8c00"
cursor_border = "#ff8c00"
cursor_fg = "#cde1ee"
selection_bg = "#b4c7d4"
selection_fg = "#2e404b"
split = "#ff8c00"
compose_cursor = "#f57400"
scrollbar_thumb = "#47687c"

ansi = [
  "#47687c", # black
  "#7295aa", # dark_red
  "#63859a", # dark_green
  "#f57400", # dark_yellow
  "#55778b", # dark_blue
  "#63859a", # dark_magenta
  "#7295aa", # dark_cyan
  "#b4c7d4" # light_gray
]

brights = [
  "#47687c", # gray
  "#7295aa", # red
  "#63859a", # green
  "#ff8c00", # yellow
  "#55778b", # blue
  "#63859a", # magenta
  "#7295aa", # cyan
  "#c0d4e1" # white
]

[colors.tab_bar]
inactive_tab_edge = "#c0d4e1"
background = "#cde1ee"

[colors.tab_bar.active_tab]
fg_color = "#c0d4e1"
bg_color = "#ff8c00"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#c0d4e1"
bg_color = "#b4c7d4"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c0d4e1"
bg_color = "#c0d4e1"

[colors.tab_bar.new_tab]
fg_color = "#c0d4e1"
bg_color = "#3aa85b"

[colors.tab_bar.new_tab_hover]
fg_color = "#c0d4e1"
bg_color = "#c0d4e1"
intensity = "Bold"