[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ E-Ink Light"

[colors]
foreground = "#2e2e2e"
background = "#dedede"
cursor_bg = "#5f5155"
cursor_border = "#5f5155"
cursor_fg = "#dedede"
selection_bg = "#c4c4c4"
selection_fg = "#2e2e2e"
split = "#5f5155"
compose_cursor = "#ea3c3f"
scrollbar_thumb = "#5d5d5d"

ansi = [
  "#5d5d5d", # black
  "#808080", # dark_red
  "#747474", # dark_green
  "#747474", # dark_yellow
  "#696969", # dark_blue
  "#747474", # dark_magenta
  "#808080", # dark_cyan
  "#c4c4c4" # light_gray
]

brights = [
  "#5d5d5d", # gray
  "#808080", # red
  "#747474", # green
  "#747474", # yellow
  "#696969", # blue
  "#747474", # magenta
  "#808080", # cyan
  "#d1d1d1" # white
]

[colors.tab_bar]
inactive_tab_edge = "#d1d1d1"
background = "#dedede"

[colors.tab_bar.active_tab]
fg_color = "#d1d1d1"
bg_color = "#5f5155"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#d1d1d1"
bg_color = "#c4c4c4"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d1d1d1"
bg_color = "#d1d1d1"

[colors.tab_bar.new_tab]
fg_color = "#d1d1d1"
bg_color = "#839d00"

[colors.tab_bar.new_tab_hover]
fg_color = "#d1d1d1"
bg_color = "#d1d1d1"
intensity = "Bold"