[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ Clay Light"

[colors]
foreground = "#322e22"
background = "#f2efe0"
cursor_bg = "#e76b3e"
cursor_border = "#e76b3e"
cursor_fg = "#f2efe0"
selection_bg = "#d2cebf"
selection_fg = "#322e22"
split = "#e76b3e"
compose_cursor = "#e76b3e"
scrollbar_thumb = "#5d553f"

ansi = [
  "#5d553f", # black
  "#888069", # dark_red
  "#79715a", # dark_green
  "#79715a", # dark_yellow
  "#6b634d", # dark_blue
  "#79715a", # dark_magenta
  "#888069", # dark_cyan
  "#d2cebf" # light_gray
]

brights = [
  "#5d553f", # gray
  "#888069", # red
  "#79715a", # green
  "#79715a", # yellow
  "#6b634d", # blue
  "#79715a", # magenta
  "#888069", # cyan
  "#d2cebf" # white
]

[colors.tab_bar]
inactive_tab_edge = "#e2ded0"
background = "#f2efe0"

[colors.tab_bar.active_tab]
fg_color = "#e2ded0"
bg_color = "#e76b3e"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e2ded0"
bg_color = "#d2cebf"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e2ded0"
bg_color = "#e2ded0"

[colors.tab_bar.new_tab]
fg_color = "#e2ded0"
bg_color = "#8aab67"

[colors.tab_bar.new_tab_hover]
fg_color = "#e2ded0"
bg_color = "#e2ded0"
intensity = "Bold"