[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ 47 Dark"

[colors]
foreground = "#ffe7c7"
background = "#20231b"
cursor_bg = "#3dc7a9"
cursor_border = "#3dc7a9"
cursor_fg = "#20231b"
selection_bg = "#434b36"
selection_fg = "#ffe7c7"
split = "#3dc7a9"
compose_cursor = "#fe886a"
scrollbar_thumb = "#7a8568"

ansi = [
  "#5d684c", # black
  "#98a485", # dark_red
  "#3dc7a9", # dark_green
  "#fa8e3c", # dark_yellow
  "#6b765a", # dark_blue
  "#7a8568", # dark_magenta
  "#98a485", # dark_cyan
  "#e5cdad" # light_gray
]

brights = [
  "#5d684c", # gray
  "#98a485", # red
  "#3dc7a9", # green
  "#fa8e3c", # yellow
  "#6b765a", # blue
  "#7a8568", # magenta
  "#98a485", # cyan
  "#f2daba" # white
]

[colors.tab_bar]
inactive_tab_edge = "#151712"
background = "#20231b"

[colors.tab_bar.active_tab]
fg_color = "#20231b"
bg_color = "#3dc7a9"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#20231b"
bg_color = "#434b36"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#20231b"
bg_color = "#373d2f"

[colors.tab_bar.new_tab]
fg_color = "#20231b"
bg_color = "#3dc7a9"

[colors.tab_bar.new_tab_hover]
fg_color = "#20231b"
bg_color = "#373d2f"
intensity = "Bold"