[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ Osman Light"

[colors]
foreground = "#38312b"
background = "#fff7f0"
cursor_bg = "#0184ff"
cursor_border = "#0184ff"
cursor_fg = "#fff7f0"
selection_bg = "#cac3bc"
selection_fg = "#38312b"
split = "#0184ff"
compose_cursor = "#f03328"
scrollbar_thumb = "#6c6158"

ansi = [
  "#6c6158", # black
  "#f03328", # dark_red
  "#897e74", # dark_green
  "#897e74", # dark_yellow
  "#0184ff", # dark_blue
  "#897e74", # dark_magenta
  "#988d83", # dark_cyan
  "#cac3bc" # light_gray
]

brights = [
  "#6c6158", # gray
  "#f03328", # red
  "#897e74", # green
  "#897e74", # yellow
  "#0184ff", # blue
  "#897e74", # magenta
  "#988d83", # cyan
  "#cac3bc" # white
]

[colors.tab_bar]
inactive_tab_edge = "#d7cfc9"
background = "#fff7f0"

[colors.tab_bar.active_tab]
fg_color = "#d7cfc9"
bg_color = "#0184ff"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#d7cfc9"
bg_color = "#cac3bc"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d7cfc9"
bg_color = "#d7cfc9"

[colors.tab_bar.new_tab]
fg_color = "#d7cfc9"
bg_color = "#3aa85b"

[colors.tab_bar.new_tab_hover]
fg_color = "#d7cfc9"
bg_color = "#d7cfc9"
intensity = "Bold"