[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ Orange Light"

[colors]
foreground = "#242a2c"
background = "#d7e0e3"
cursor_bg = "#ee7c00"
cursor_border = "#ee7c00"
cursor_fg = "#d7e0e3"
selection_bg = "#bdc6c9"
selection_fg = "#242a2c"
split = "#ee7c00"
compose_cursor = "#e76700"
scrollbar_thumb = "#585f61"

ansi = [
  "#585f61", # black
  "#9ea6a9", # dark_red
  "#868e90", # dark_green
  "#e76700", # dark_yellow
  "#747c7e", # dark_blue
  "#868e90", # dark_magenta
  "#9ea6a9", # dark_cyan
  "#bdc6c9" # light_gray
]

brights = [
  "#585f61", # gray
  "#9ea6a9", # red
  "#868e90", # green
  "#ee7c00", # yellow
  "#747c7e", # blue
  "#868e90", # magenta
  "#9ea6a9", # cyan
  "#bdc6c9" # white
]

[colors.tab_bar]
inactive_tab_edge = "#cad3d5"
background = "#d7e0e3"

[colors.tab_bar.active_tab]
fg_color = "#cad3d5"
bg_color = "#ee7c00"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#cad3d5"
bg_color = "#bdc6c9"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#cad3d5"
bg_color = "#cad3d5"

[colors.tab_bar.new_tab]
fg_color = "#cad3d5"
bg_color = "#3aa85b"

[colors.tab_bar.new_tab_hover]
fg_color = "#cad3d5"
bg_color = "#cad3d5"
intensity = "Bold"