[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ E-Ink Dark"

[colors]
foreground = "#dedede"
background = "#2e2e2e"
cursor_bg = "#bdacb0"
cursor_border = "#bdacb0"
cursor_fg = "#2e2e2e"
selection_bg = "#424242"
selection_fg = "#dedede"
split = "#bdacb0"
compose_cursor = "#dd7577"
scrollbar_thumb = "#8c8c8c"

ansi = [
  "#5d5d5d", # black
  "#a4a4a4", # dark_red
  "#8c8c8c", # dark_green
  "#8c8c8c", # dark_yellow
  "#7a7a7a", # dark_blue
  "#8c8c8c", # dark_magenta
  "#a4a4a4", # dark_cyan
  "#c4c4c4" # light_gray
]

brights = [
  "#5d5d5d", # gray
  "#a4a4a4", # red
  "#8c8c8c", # green
  "#8c8c8c", # yellow
  "#7a7a7a", # blue
  "#8c8c8c", # magenta
  "#a4a4a4", # cyan
  "#c4c4c4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#242424"
background = "#2e2e2e"

[colors.tab_bar.active_tab]
fg_color = "#2e2e2e"
bg_color = "#bdacb0"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#2e2e2e"
bg_color = "#424242"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#2e2e2e"
bg_color = "#383838"

[colors.tab_bar.new_tab]
fg_color = "#2e2e2e"
bg_color = "#a9ba78"

[colors.tab_bar.new_tab_hover]
fg_color = "#2e2e2e"
bg_color = "#383838"
intensity = "Bold"