[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ ITA Light"

[colors]
foreground = "#161616"
background = "#fcfcfc"
cursor_bg = "#199c38"
cursor_border = "#199c38"
cursor_fg = "#fcfcfc"
selection_bg = "#dedede"
selection_fg = "#161616"
split = "#199c38"
compose_cursor = "#ef343b"
scrollbar_thumb = "#8c8c8c"

ansi = [
  "#3d3d3d", # black
  "#c4c4c4", # dark_red
  "#b1b1b1", # dark_green
  "#b1b1b1", # dark_yellow
  "#c4c4c4", # dark_blue
  "#b1b1b1", # dark_magenta
  "#c4c4c4", # dark_cyan
  "#c4c4c4" # light_gray
]

brights = [
  "#8c8c8c", # gray
  "#c4c4c4", # red
  "#b1b1b1", # green
  "#b1b1b1", # yellow
  "#c4c4c4", # blue
  "#b1b1b1", # magenta
  "#c4c4c4", # cyan
  "#c4c4c4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#eeeeee"
background = "#fcfcfc"

[colors.tab_bar.active_tab]
fg_color = "#eeeeee"
bg_color = "#199c38"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#eeeeee"
bg_color = "#dedede"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#eeeeee"
bg_color = "#eeeeee"

[colors.tab_bar.new_tab]
fg_color = "#eeeeee"
bg_color = "#199c38"

[colors.tab_bar.new_tab_hover]
fg_color = "#eeeeee"
bg_color = "#eeeeee"
intensity = "Bold"