[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNM ∷ E-Ink Light"

[colors]
foreground = "#292929"
background = "#dedede"
cursor_bg = "#5f5155"
cursor_border = "#5f5155"
cursor_fg = "#dedede"
selection_bg = "#c4c4c4"
selection_fg = "#292929"
split = "#5f5155"
compose_cursor = "#f14d4c"
scrollbar_thumb = "#5d5d5d"

ansi = [
  "#5d5d5d", # black
  "#a4a4a4", # dark_red
  "#8c8c8c", # dark_green
  "#8c8c8c", # dark_yellow
  "#7a7a7a", # dark_blue
  "#8c8c8c", # dark_magenta
  "#a4a4a4", # dark_cyan
  "#c4c4c4" # light_gray
]

brights = [
  "#5d5d5d", # gray
  "#a4a4a4", # red
  "#8c8c8c", # green
  "#8c8c8c", # yellow
  "#7a7a7a", # blue
  "#8c8c8c", # magenta
  "#a4a4a4", # cyan
  "#c4c4c4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#d1d1d1"
background = "#dedede"

[colors.tab_bar.active_tab]
fg_color = "#d1d1d1"
bg_color = "#5f5155"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#d1d1d1"
bg_color = "#c4c4c4"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d1d1d1"
bg_color = "#d1d1d1"

[colors.tab_bar.new_tab]
fg_color = "#d1d1d1"
bg_color = "#819e00"

[colors.tab_bar.new_tab_hover]
fg_color = "#d1d1d1"
bg_color = "#d1d1d1"
intensity = "Bold"