[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Summer Day"

[colors]
foreground = "#0d3025"
background = "#f9eddd"
cursor_bg = "#f9b520"
cursor_border = "#f9b520"
cursor_fg = "#f9eddd"
selection_bg = "#fef3e7"
selection_fg = "#0d3025"
split = "#f9b520"
compose_cursor = "#d53d00"
scrollbar_thumb = "#4f6b58"

ansi = [
  "#1e4334", # black
  "#b72200", # dark_red
  "#326234", # dark_green
  "#f69a22", # dark_yellow
  "#005c62", # dark_blue
  "#a6344f", # dark_magenta
  "#0f6353", # dark_cyan
  "#e9ddc4" # light_gray
]

brights = [
  "#6a816e", # gray
  "#d53d00", # red
  "#397949", # green
  "#f9b520", # yellow
  "#007677", # blue
  "#c04d6e", # magenta
  "#237961", # cyan
  "#f9eddd" # white
]

[colors.tab_bar]
inactive_tab_edge = "#f3e6d2"
background = "#f9eddd"

[colors.tab_bar.active_tab]
fg_color = "#f9eddd"
bg_color = "#f9b520"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#f9eddd"
bg_color = "#829582"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#f9eddd"
bg_color = "#e9ddc4"

[colors.tab_bar.new_tab]
fg_color = "#f9eddd"
bg_color = "#397949"

[colors.tab_bar.new_tab_hover]
fg_color = "#f9eddd"
bg_color = "#e9ddc4"
intensity = "Bold"
