[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Winter Night"

[colors]
foreground = "#e2e8f2"
background = "#12161d"
cursor_bg = "#fba952"
cursor_border = "#fba952"
cursor_fg = "#12161d"
selection_bg = "#212f3f"
selection_fg = "#e2e8f2"
split = "#fba952"
compose_cursor = "#a8a6e5"
scrollbar_thumb = "#6f8298"

ansi = [
  "#212f3f", # black
  "#9790c7", # dark_red
  "#74a8b8", # dark_green
  "#eb8656", # dark_yellow
  "#729bcf", # dark_blue
  "#9f8fbe", # dark_magenta
  "#64b3c0", # dark_cyan
  "#c0ccdb" # light_gray
]

brights = [
  "#3f556b", # gray
  "#a8a6e5", # red
  "#82c3d3", # green
  "#fba952", # yellow
  "#7fb6ee", # blue
  "#b4a7df", # magenta
  "#71cfd9", # cyan
  "#e2e8f2" # white
]

[colors.tab_bar]
inactive_tab_edge = "#0b0d12"
background = "#12161d"

[colors.tab_bar.active_tab]
fg_color = "#12161d"
bg_color = "#fba952"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#12161d"
bg_color = "#3f556b"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#12161d"
bg_color = "#1a222e"

[colors.tab_bar.new_tab]
fg_color = "#12161d"
bg_color = "#82c3d3"

[colors.tab_bar.new_tab_hover]
fg_color = "#12161d"
bg_color = "#1a222e"
intensity = "Bold"
