[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Summer Night"

[colors]
foreground = "#eae0cf"
background = "#001b1a"
cursor_bg = "#f3b94c"
cursor_border = "#f3b94c"
cursor_fg = "#001b1a"
selection_bg = "#14342f"
selection_fg = "#eae0cf"
split = "#f3b94c"
compose_cursor = "#e2805e"
scrollbar_thumb = "#849581"

ansi = [
  "#14342f", # black
  "#c16d45", # dark_red
  "#59985b", # dark_green
  "#ea9941", # dark_yellow
  "#00848b", # dark_blue
  "#ba6c78", # dark_magenta
  "#339a83", # dark_cyan
  "#c8bda1" # light_gray
]

brights = [
  "#3c5444", # gray
  "#e2805e", # red
  "#69ba7c", # green
  "#f3b94c", # yellow
  "#00a5a6", # blue
  "#d88095", # magenta
  "#51bb9a", # cyan
  "#eae0cf" # white
]

[colors.tab_bar]
inactive_tab_edge = "#001111"
background = "#001b1a"

[colors.tab_bar.active_tab]
fg_color = "#001b1a"
bg_color = "#f3b94c"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#001b1a"
bg_color = "#3c5444"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#001b1a"
bg_color = "#042824"

[colors.tab_bar.new_tab]
fg_color = "#001b1a"
bg_color = "#69ba7c"

[colors.tab_bar.new_tab_hover]
fg_color = "#001b1a"
bg_color = "#042824"
intensity = "Bold"
