[metadata]
author = "Black Atom Industries"
name = "Black Atom — JPN ∷ Koyo Yoru"

[colors]
foreground = "#fbcaa4"
background = "#35293a"
cursor_bg = "#edaa4b"
cursor_border = "#edaa4b"
cursor_fg = "#35293a"
selection_bg = "#4d4053"
selection_fg = "#fbcaa4"
split = "#edaa4b"
compose_cursor = "#e47889"
scrollbar_thumb = "#9c98b3"

ansi = [
  "#4d4053", # black
  "#d56b7c", # dark_red
  "#4fa480", # dark_green
  "#fd9e66", # dark_yellow
  "#958aab", # dark_blue
  "#d08c63", # dark_magenta
  "#719b8f", # dark_cyan
  "#ecbd96" # light_gray
]

brights = [
  "#605872", # gray
  "#e47889", # red
  "#5db28d", # green
  "#edaa4b", # yellow
  "#a298b9", # blue
  "#eda77d", # magenta
  "#7ea99c", # cyan
  "#fbcaa4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#291d2e"
background = "#35293a"

[colors.tab_bar.active_tab]
fg_color = "#35293a"
bg_color = "#edaa4b"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#35293a"
bg_color = "#605872"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#35293a"
bg_color = "#413446"

[colors.tab_bar.new_tab]
fg_color = "#35293a"
bg_color = "#5db28d"

[colors.tab_bar.new_tab_hover]
fg_color = "#35293a"
bg_color = "#413446"
intensity = "Bold"
