[metadata]
author = "Black Atom Industries"
name = "Black Atom â€” Light"

[colors]
foreground = "#28292a"
background = "#ecefef"
cursor_bg = "#009c67"
cursor_border = "#009c67"
cursor_fg = "#ecefef"
selection_bg = "#d5d8d8"
selection_fg = "#28292a"
split = "#009c67"
compose_cursor = "#c70050"
scrollbar_thumb = "#51606b"

ansi = [
  "#3c3d3e", # black
  "#97a7b3", # dark_red
  "#7f8f9a", # dark_green
  "#7f8f9a", # dark_yellow
  "#687782", # dark_blue
  "#007a1f", # dark_magenta
  "#009c67", # dark_cyan
  "#e2e5e5" # light_gray
]

brights = [
  "#51606b", # gray
  "#97a7b3", # red
  "#7f8f9a", # green
  "#7f8f9a", # yellow
  "#687782", # blue
  "#007a1f", # magenta
  "#009c67", # cyan
  "#ecefef" # white
]

[colors.tab_bar]
inactive_tab_edge = "#e2e5e5"
background = "#ecefef"

[colors.tab_bar.active_tab]
fg_color = "#e2e5e5"
bg_color = "#009c67"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e2e5e5"
bg_color = "#d5d8d8"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e2e5e5"
bg_color = "#e2e5e5"

[colors.tab_bar.new_tab]
fg_color = "#e2e5e5"
bg_color = "#008400"

[colors.tab_bar.new_tab_hover]
fg_color = "#e2e5e5"
bg_color = "#e2e5e5"
intensity = "Bold"