[metadata]
author = "Black Atom Industries"
name = "Black Atom â€” Light Dimmed"

[colors]
foreground = "#272929"
background = "#dfe2e2"
cursor_bg = "#009c67"
cursor_border = "#009c67"
cursor_fg = "#dfe2e2"
selection_bg = "#c8cbcb"
selection_fg = "#272929"
split = "#009c67"
compose_cursor = "#c70050"
scrollbar_thumb = "#676969"

ansi = [
  "#676969", # black
  "#a9abab", # dark_red
  "#909393", # dark_green
  "#909393", # dark_yellow
  "#787b7b", # dark_blue
  "#007a1f", # dark_magenta
  "#009c67", # dark_cyan
  "#c8cbcb" # light_gray
]

brights = [
  "#676969", # gray
  "#a9abab", # red
  "#909393", # green
  "#909393", # yellow
  "#787b7b", # blue
  "#007a1f", # magenta
  "#009c67", # cyan
  "#c8cbcb" # white
]

[colors.tab_bar]
inactive_tab_edge = "#d5d8d8"
background = "#dfe2e2"

[colors.tab_bar.active_tab]
fg_color = "#d5d8d8"
bg_color = "#009c67"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#d5d8d8"
bg_color = "#c8cbcb"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d5d8d8"
bg_color = "#d5d8d8"

[colors.tab_bar.new_tab]
fg_color = "#d5d8d8"
bg_color = "#008400"

[colors.tab_bar.new_tab_hover]
fg_color = "#d5d8d8"
bg_color = "#d5d8d8"
intensity = "Bold"