[metadata]
author = "Black Atom Industries"
name = "Black Atom â€” Dark"

[colors]
foreground = "#e2e5e5"
background = "#0c0e0e"
cursor_bg = "#66c3a4"
cursor_border = "#66c3a4"
cursor_fg = "#0c0e0e"
selection_bg = "#1e2020"
selection_fg = "#e2e5e5"
split = "#66c3a4"
compose_cursor = "#e97292"
scrollbar_thumb = "#7e8181"

ansi = [
  "#1e2020", # black
  "#9c9f9f", # dark_red
  "#7e8181", # dark_green
  "#7e8181", # dark_yellow
  "#676969", # dark_blue
  "#59a174", # dark_magenta
  "#66c3a4", # dark_cyan
  "#cfd1d1" # light_gray
]

brights = [
  "#535656", # gray
  "#9c9f9f", # red
  "#7e8181", # green
  "#7e8181", # yellow
  "#676969", # blue
  "#59a174", # magenta
  "#66c3a4", # cyan
  "#e2e5e5" # white
]

[colors.tab_bar]
inactive_tab_edge = "#050606"
background = "#0c0e0e"

[colors.tab_bar.active_tab]
fg_color = "#0c0e0e"
bg_color = "#66c3a4"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#0c0e0e"
bg_color = "#1e2020"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#0c0e0e"
bg_color = "#151616"

[colors.tab_bar.new_tab]
fg_color = "#0c0e0e"
bg_color = "#4cb86a"

[colors.tab_bar.new_tab_hover]
fg_color = "#0c0e0e"
bg_color = "#151616"
intensity = "Bold"