[metadata]
author = "Black Atom Industries"
name = "Black Atom â€” Dark"

[colors]
foreground = "#c9dae7"
background = "#111817"
cursor_bg = "#66c3a4"
cursor_border = "#66c3a4"
cursor_fg = "#111817"
selection_bg = "#232a2a"
selection_fg = "#c9dae7"
split = "#66c3a4"
compose_cursor = "#e97292"
scrollbar_thumb = "#73838e"

ansi = [
  "#232a2a", # black
  "#91a1ad", # dark_red
  "#73838e", # dark_green
  "#73838e", # dark_yellow
  "#5c6b76", # dark_blue
  "#59a174", # dark_magenta
  "#66c3a4", # dark_cyan
  "#b6c7d3" # light_gray
]

brights = [
  "#495762", # gray
  "#91a1ad", # red
  "#73838e", # green
  "#73838e", # yellow
  "#5c6b76", # blue
  "#59a174", # magenta
  "#66c3a4", # cyan
  "#c9dae7" # white
]

[colors.tab_bar]
inactive_tab_edge = "#080f0f"
background = "#111817"

[colors.tab_bar.active_tab]
fg_color = "#111817"
bg_color = "#66c3a4"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#111817"
bg_color = "#232a2a"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#111817"
bg_color = "#1a2121"

[colors.tab_bar.new_tab]
fg_color = "#111817"
bg_color = "#4cb86a"

[colors.tab_bar.new_tab_hover]
fg_color = "#111817"
bg_color = "#1a2121"
intensity = "Bold"